apiVersion: apps/v1
kind: Deployment
metadata:
  name: jhipster-kafka
  namespace: bonlimousin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jhipster-kafka
  template:
    metadata:
      labels:
        app: jhipster-kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:5.5.0
          env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: 'PLAINTEXT://jhipster-kafka.bonlimousin.svc.cluster.local:9092'
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: 'jhipster-zookeeper.bonlimousin.svc.cluster.local:2181'
            - name: KAFKA_BROKER_ID
              value: '2'
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: '1'
          ports:
            - containerPort: 9092
          resources:
            requests:
              memory: '512Mi'
              cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '1'
---
apiVersion: v1
kind: Service
metadata:
  name: jhipster-kafka
  namespace: bonlimousin
spec:
  selector:
    app: jhipster-kafka
  ports:
    - port: 9092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jhipster-zookeeper
  namespace: bonlimousin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jhipster-zookeeper
  template:
    metadata:
      labels:
        app: jhipster-zookeeper
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:5.5.0
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: '2181'
            - name: ZOOKEEPER_TICK_TIME
              value: '2000'
            - name: ZOOKEEPER_SYNC_LIMIT
              value: '2'
          ports:
            - containerPort: 2181
          resources:
            requests:
              memory: '512Mi'
              cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '1'
---
apiVersion: v1
kind: Service
metadata:
  name: jhipster-zookeeper
  namespace: bonlimousin
spec:
  selector:
    app: jhipster-zookeeper
  ports:
    - port: 2181
